GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJJc21haWwgTnVyIEEiLCJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsImlhdCI6MTY2NjE4NDgwMSwiZXhwIjoxNjY2MTg0ODE2fQ.LtBCWafTxcBTBnz48IDwGGIrRj4cE8x6I85v4uR1sHM

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Ismail Nur A",
    "email": "email@email.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout