package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"encoding/json"
	"fmt"

	restapi "github.com/itzmail/hackernews/graphql/user/RESTApi"
	generatedUser "github.com/itzmail/hackernews/graphql/user/graph/generated"
	modelUser "github.com/itzmail/hackernews/graphql/user/graph/model"
	"github.com/itzmail/hackernews/internal/links"
	"github.com/itzmail/hackernews/internal/users"
)

// Links is the resolver for the links field.
func (r *queryResolver) Links(ctx context.Context) ([]*modelUser.Link, error) {
	link := links.GetAll()
	var links []*modelUser.Link
	for _, l := range link {
		links = append(links, &modelUser.Link{
			ID:      l.ID,
			Title:   l.Title,
			Address: l.Address,
			User: &modelUser.User{
				ID:   l.User.ID,
				Name: l.User.Username,
			},
		})
	}
	return links, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*modelUser.User, error) {
	userDummy, err := restapi.FetchUsersDummy()
	if err != nil {
		return nil, err
	}
	for _, user := range userDummy.Users {
		fmt.Printf("ID: %d, Name: %s %s, Email: %s\n", user.ID, user.FirstName, user.LastName, user.Email)
	}
	user := users.GetAll()
	var users []*modelUser.User
	for _, u := range user {
		users = append(users, &modelUser.User{
			ID:   u.ID,
			Name: u.Username,
			FromAPI: func() *string {
				data, err := json.Marshal(&userDummy.Users)
				if err != nil {
					return nil
				}
				str := string(data)
				return &str
			}(),
		})
	}
	return users, nil
}

// Link is the resolver for the link field.
func (r *queryResolver) Link(ctx context.Context, id string) (*modelUser.Link, error) {
	panic(fmt.Errorf("not implemented: Link - link"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*modelUser.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Query returns generatedUser.QueryResolver implementation.
func (r *Resolver) Query() generatedUser.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
